package dok.donzul.mapper;

import dok.donzul.entity.TbMstUser;
import dok.donzul.entity.TbMstUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbMstUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	long countByExample(TbMstUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	int deleteByExample(TbMstUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	int deleteByPrimaryKey(Long indexNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	int insert(TbMstUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	int insertSelective(TbMstUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	List<TbMstUser> selectByExample(TbMstUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	TbMstUser selectByPrimaryKey(Long indexNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	int updateByExampleSelective(@Param("record") TbMstUser record, @Param("example") TbMstUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	int updateByExample(@Param("record") TbMstUser record, @Param("example") TbMstUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	int updateByPrimaryKeySelective(TbMstUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table donzul.tb_mst_user
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	int updateByPrimaryKey(TbMstUser record);
}