package dok.donzul.entity;

import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

public class TbMstUser implements UserDetails {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column donzul.tb_mst_user.index_no
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	private Long indexNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column donzul.tb_mst_user.username
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column donzul.tb_mst_user.password
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column donzul.tb_mst_user.name
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column donzul.tb_mst_user.is_account_non_expired
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	private Boolean isAccountNonExpired;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column donzul.tb_mst_user.is_account_non_locked
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	private Boolean isAccountNonLocked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column donzul.tb_mst_user.is_credentials_non_expired
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	private Boolean isCredentialsNonExpired;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column donzul.tb_mst_user.is_enabled
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	private Boolean isEnabled;

	private Collection<? extends GrantedAuthority> authorities;

	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column donzul.tb_mst_user.index_no
	 * @return  the value of donzul.tb_mst_user.index_no
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public Long getIndexNo() {
		return indexNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column donzul.tb_mst_user.index_no
	 * @param indexNo  the value for donzul.tb_mst_user.index_no
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public void setIndexNo(Long indexNo) {
		this.indexNo = indexNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column donzul.tb_mst_user.username
	 * @return  the value of donzul.tb_mst_user.username
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column donzul.tb_mst_user.username
	 * @param username  the value for donzul.tb_mst_user.username
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column donzul.tb_mst_user.password
	 * @return  the value of donzul.tb_mst_user.password
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column donzul.tb_mst_user.password
	 * @param password  the value for donzul.tb_mst_user.password
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column donzul.tb_mst_user.name
	 * @return  the value of donzul.tb_mst_user.name
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column donzul.tb_mst_user.name
	 * @param name  the value for donzul.tb_mst_user.name
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column donzul.tb_mst_user.is_account_non_expired
	 * @return  the value of donzul.tb_mst_user.is_account_non_expired
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public Boolean getIsAccountNonExpired() {
		return isAccountNonExpired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column donzul.tb_mst_user.is_account_non_expired
	 * @param isAccountNonExpired  the value for donzul.tb_mst_user.is_account_non_expired
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public void setIsAccountNonExpired(Boolean isAccountNonExpired) {
		this.isAccountNonExpired = isAccountNonExpired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column donzul.tb_mst_user.is_account_non_locked
	 * @return  the value of donzul.tb_mst_user.is_account_non_locked
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public Boolean getIsAccountNonLocked() {
		return isAccountNonLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column donzul.tb_mst_user.is_account_non_locked
	 * @param isAccountNonLocked  the value for donzul.tb_mst_user.is_account_non_locked
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public void setIsAccountNonLocked(Boolean isAccountNonLocked) {
		this.isAccountNonLocked = isAccountNonLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column donzul.tb_mst_user.is_credentials_non_expired
	 * @return  the value of donzul.tb_mst_user.is_credentials_non_expired
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public Boolean getIsCredentialsNonExpired() {
		return isCredentialsNonExpired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column donzul.tb_mst_user.is_credentials_non_expired
	 * @param isCredentialsNonExpired  the value for donzul.tb_mst_user.is_credentials_non_expired
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public void setIsCredentialsNonExpired(Boolean isCredentialsNonExpired) {
		this.isCredentialsNonExpired = isCredentialsNonExpired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column donzul.tb_mst_user.is_enabled
	 * @return  the value of donzul.tb_mst_user.is_enabled
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public Boolean getIsEnabled() {
		return isEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column donzul.tb_mst_user.is_enabled
	 * @param isEnabled  the value for donzul.tb_mst_user.is_enabled
	 * @mbg.generated  Tue Aug 21 00:32:08 JST 2018
	 */
	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		// TODO Auto-generated method stub
		return this.authorities;
	}

	@Override
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
//		return getIsAccountNonExpired();
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
//		return getIsAccountNonLocked();
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
//		return getIsCredentialsNonExpired();
		return true;
	}

	@Override
	public boolean isEnabled() {
		// TODO Auto-generated method stub
//		return getIsEnabled();
		return true;
	}

	public void setAuthorities(Collection<? extends GrantedAuthority> authorities) {
		this.authorities = authorities;
	}
}