package dok.donzul.entity;

public class TbMstUserAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donzul.tb_mst_user_authority.index_no
     *
     * @mbg.generated Tue Aug 21 00:32:08 JST 2018
     */
    private Long indexNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donzul.tb_mst_user_authority.username
     *
     * @mbg.generated Tue Aug 21 00:32:08 JST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donzul.tb_mst_user_authority.authority_name
     *
     * @mbg.generated Tue Aug 21 00:32:08 JST 2018
     */
    private String authorityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donzul.tb_mst_user_authority.index_no
     *
     * @return the value of donzul.tb_mst_user_authority.index_no
     *
     * @mbg.generated Tue Aug 21 00:32:08 JST 2018
     */
    public Long getIndexNo() {
        return indexNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donzul.tb_mst_user_authority.index_no
     *
     * @param indexNo the value for donzul.tb_mst_user_authority.index_no
     *
     * @mbg.generated Tue Aug 21 00:32:08 JST 2018
     */
    public void setIndexNo(Long indexNo) {
        this.indexNo = indexNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donzul.tb_mst_user_authority.username
     *
     * @return the value of donzul.tb_mst_user_authority.username
     *
     * @mbg.generated Tue Aug 21 00:32:08 JST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donzul.tb_mst_user_authority.username
     *
     * @param username the value for donzul.tb_mst_user_authority.username
     *
     * @mbg.generated Tue Aug 21 00:32:08 JST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donzul.tb_mst_user_authority.authority_name
     *
     * @return the value of donzul.tb_mst_user_authority.authority_name
     *
     * @mbg.generated Tue Aug 21 00:32:08 JST 2018
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donzul.tb_mst_user_authority.authority_name
     *
     * @param authorityName the value for donzul.tb_mst_user_authority.authority_name
     *
     * @mbg.generated Tue Aug 21 00:32:08 JST 2018
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName;
    }
}